version: "3.9"
services:
  server1:
    container_name: server-node-1
    build: ../server
    volumes:
      - ../certs:/certs
#    ports:
#      - "8080:8080"
    environment:
      SERVER_PORT: "8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/server.api/actuator/health"]
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    networks:
      - server-network

  server2:
    container_name: server-node-2
    build: ../server
    volumes:
      - ../certs:/certs
    #    ports:
    #      - "8081:8081"
    environment:
      SERVER_PORT: "8081"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/server.api/actuator/health" ]
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    networks:
      - server-network

  client:
    container_name: client
    build: ../client
    volumes:
      - ../certs:/certs
    ports:
      - "8444:8444"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8444/client.api/actuator/health", "--insecure"]
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    networks:
      - client-network

  myhaproxy:
    container_name: my-haproxy
    build: ./
    volumes:
      - ../certs:/certs
    ports:
      - "8443:8443"
      - "8445:8445"
    networks:
      - server-network
    depends_on:
      - server1
      - server2

networks:
  server-network:
    driver: bridge
  client-network:
    driver: bridge